#!/bin/sh
echo " Please enter C for Cisco and B for Brocade "
read SWITCH
case $SWITCH in
b|B)
echo "***************************************"
echo "***************************************"
echo "   SETTING BROCADE CEE PORTS ON/OFF   *"
echo "***************************************"
echo "***************************************"
echo " Please enter the BROCADE SWITCH IP "
read SWITCHIP
echo " Please enter the First CEE Port , EX: 0/1 "
read PORT1
echo " Please enter the Second CEE Port , EX: 0/2 "
read PORT2
echo " Please enter the Third CEE Port , EX: 0/3 "
read PORT3
echo " Please enter the Fourth CEE Port , EX: 0/4 "
read PORT4
while true
do
  ( sleep 5
  echo admin
  sleep 2
  echo Qlogic01
  sleep 2
  echo cmsh
  sleep 2
  echo config t
  sleep 2
  echo interface TenGigabitethernet $PORT1 
  sleep 2
  echo shut
  sleep 10
  echo no shutdown
  sleep 60
  echo interface TenGigabitethernet $PORT2 
  sleep 2
  echo shut
  sleep 10
  echo no shutdown
  sleep 60
  echo interface TenGigabitethernet $PORT3 
  sleep 2
  echo shut
  sleep 15
  echo no shutdown
  sleep 120
  echo interface TenGigabitethernet $PORT4 
  sleep 2
  echo shut
  sleep 10
  echo no shutdown
  sleep 60
  echo exit
  sleep 2
  echo exit
  sleep 2
  echo exit
  sleep 200
) | telnet $SWITCHIP
done
 ;;
  c|C)
echo "========================================"
echo "I    SETTING CISCO PORTS ON/OFF         "
echo "========================================"
echo "Please enter the Cisco Switch IP"
read SWITCHIP
echo "Enter 1st port number (example: eth1/1)"
read PORT1
echo "Enter 2nd port number (example: eth1/2)"
read PORT2
echo "Enter 3rd port number (example: eth1/3) or (Repeat same port# if necessary)"
read PORT3
echo "Enter 4th port number (example: eth1/4) or (Repeat same port# if necessary)"
read PORT4
while true
do
( sleep 3
  echo admin
  sleep 3
  echo Qlogic01 
  sleep 3
  echo config t
  echo int $PORT1
  echo shut
  sleep 5
  echo no shut
  sleep 60
  echo int $PORT2
  echo shut
  sleep 5
  echo no shut
  sleep 60
  echo int $PORT3
  echo shut
  sleep 5
  echo no shut
  sleep 60
  echo int $PORT4
  echo shut
  sleep 5
  echo no shut
  sleep 60
  echo exit
  sleep 2
  echo exit
  sleep 2
  echo exit
  sleep 600
)| telnet $SWITCHIP 2>&1
done
;;
*)
esac
